### ISSUE TITLE
Cannot find package 'esbuild' when run with npx

### ISSUE THREAD

**Issue by erkage** [hyrious/import-cost#1]
Hi,

Came from your vscode extension of this because it doesn't work for me so I started to look for a solution here.

So I've tried to run `npx @hyrious/import-cost foo.vue` and I got `Cannot find package 'esbuild' imported from /Users/erkage/.npm/_npx/0e2a14ad39214621/node_modules/@hyrious/import-cost/dist/index.mjs`.

Then I installed esbuild globally with `npm i -g esbuild` but it didn't helped.

Any suggestion? Thanks!

system info: Apple M1 Pro / MacOS 13.1
npm: 9.6.4

**Comment by hyrious** [comment]
This is probably because of I'm setting esbuild as an optional peer dependency and npx wouldn't install it automatically like normal peer dependencies.

The purpose of doing that was because I have an option `esbuildPath` which can be set from the outside without really depending on esbuild. This way I can use user's global esbuild in the vscode extension. But with npx it is still depending on that.

So, I will remove the "optional" setting from package.json to let npx happy. On the other hand, since you've installed esbuild globally, it should make the vscode extension work now. Can you help me confirm that?

To make it clear, the vscode extension will try load esbuild in these steps:

```js
import cp from 'child_process'
import os from 'os'
import {join} from 'path'

const npm = os.platform() === 'win32' ? 'npm.cmd' : 'npm'
const npmRoot = spawnSync(npm, ['root', '-g'], {shell: true, encoding: 'utf8'}).stdout.trim()
const esbuildPath = join(npmRoot, 'esbuild/lib/main.js')

import(esbuildPath).then(esbuild => console.log(esbuild.version))
```

That is to say, the extension made the assumption that your globally installed esbuild should be at

```bash
ls $(npm root -g)/esbuild/lib/main.js
```

You can try that command in your terminal to see if it's there.

**Comment by hyrious** [comment]
> So, I will remove the "optional" setting from package.json to let npx happy.

🚢 0.1.3

**Comment by erkage** [comment]
Thanks for your detailed answer 🙂.

> On the other hand, since you've installed esbuild globally, it should make the vscode extension work now. Can you help me confirm that?

Yes I can confirm that it's working fine now.

**Comment by hyrious** [comment]
Good to hear that! I'm going to close this issue since it is solved.
